workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    environment:
      groups:
        - env
      node: latest
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Set up keys
        script: |
          echo "APIALLNEWS=$APIALLNEWS" >> "$FCI_BUILD_DIR/android/local.properties"
          echo "APIKEY=$APIKEY" >> "$FCI_BUILD_DIR/android/local.properties"
          echo "APINEWS=$APINEWS" >> "$FCI_BUILD_DIR/android/local.properties"
      - name: Set up app/build.gradle
        script: |
          mv ./support-files/build.gradle android/app
    artifacts:
      - android/app/build/outputs/**/*.apk

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      groups:
        - env
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Set up keys
        script: |
          echo "APIALLNEWS=$APIALLNEWS" >> "$FCI_BUILD_DIR/ios/Runner/Config.xcconfig"
          echo "APIKEY=$APIKEY" >> "$FCI_BUILD_DIR/ios/Runner/Config.xcconfig"
          echo "APINEWS=$APINEWS" >> "$FCI_BUILD_DIR/ios/Runner/Config.xcconfig"
    artifacts:
      - build/ios/*.ipa
